version: "3.9"

services:
  webserver:
    build: .
    ports:
      - "80:80"
    volumes:
      - myvolume:/usr/share/nginx/html
    container_name: mycontainer

volumes:
  myvolume:
    driver: local
